### ISSUE TITLE
In 1.20.1-0.5.1 version thereis an item missing key value

### ISSUE THREAD

**Issue by QiuShui1012** [ChefMooon/ubes-delight#13]
![4B03E7C9475AE72649414CAC32C36D0D](https://github.com/ChefMooon/ubes-delight/assets/150409561/bb1c73da-c39b-423f-b1f2-d9d7ddd84054)
Bamboo Baking Mat's tooltip was gone.
![AEB36A43D5EFA433AF6B379D7C1C0699](https://github.com/ChefMooon/ubes-delight/assets/150409561/c6911545-57ba-4bdc-8558-dd62fa0d7fcf)
And I can't find it in en_us.json too.
I hope the author can add the text of this key value as soon as possible.

**Operating System**
Windows 11 家庭中文版 22621.2861
**Mod Version**
1.20.1-0.5.1
**Minecraft Version**
1.20.1
**Fabric/Forge Version**
Fabric
**Other Mods**
I think this bug has nothing to do with other modules.

(Some sentences are translated by machine because I am not good at English.)
(And I'm going to make zh_cn.json. Will you merge it into the code?)

**Comment by ChefMooon** [comment]
Appreciate you opening the bug and filling out the information! The tooltip has been removed as it should not be there, fixed with this push 0583fc05d0ad55de47902908ffa4cbb550e9b6d8. I will release a minor update with the fix as well v0.1.5a. 

That would be amazing if you made a zh_cn.json I would happily merge it. some of the names could be better described, if you have any questions you can find me in the [Chef's Hub Discord](https://discord.gg/mbuDBHHUws). I am going to merge all the language additions in the new year.
