### ISSUE TITLE
[Forge 1.20.1] Composters Can Compost Nothing With Ube's Delight Installed

### ISSUE THREAD

**Issue by RegalRuffRaff** [ChefMooon/ubes-delight#23]
With Ube's Delight installed, composters allow Players to get free bonemeal by right-clicking the block empty-handed. It treats an empty hand as a guaranteed compost stage, despite nothing being put into the block. Tested this with Ube's Delight installed, then removed to see if it was another mod causing this issue.

To Reproduce
1. Place down a Composter.
2. Interact with the Composter (right-click) to see what occurs.

Windows 10

Ube's Delight 0.2.0

Minecraft 1.20.1

Forge 47.3.0

Everything else seems to work fine with the exception of the Composter's unexpected behavior.

**Comment by ChefMooon** [comment]
Really appreciate the testing and the bug report! This should definitely not be happening, I’ll ensure it gets fixed in the next update. Since it’s not a critical issue, I’ll wait a few days to see if any other feedback comes in before pushing the update. I’ll close this report once the update is released. Thank you!
